
local-multi:
	docker-compose -f docker-compose-multi.yml up -d

local-multi-down:
	docker-compose -f docker-compose-multi.yml down

local-update-multi:
	docker-compose -f docker-compose-multi.yml restart nkmpp-1 && docker-compose -f docker-compose-multi.yml restart nkmpp-2
